#!/bin/bash

#############################################
# DSBS - Digital Signage Background Schedule
#
# ctime: 2016-08-25 /TR
# mtime: 2016-08-25 /TR
#
# version: 0.3
#
# -> run it via cron like this:
# */1 * * * * /usr/sbin/dsbd "dsb1"
# */1 * * * * /usr/sbin/dsbd "dsb-xxl"
#############################################

SMB_PREFIX="/home/dsb"
WEB_PREFIX="/var/www/html/dsb"

# uncomment for testing @ ./$NAME/...
SMB_PREFIX="."
WEB_PREFIX="."

if [ -z $1 ]; then
  echo "Need exact one parameter!"
  exit 1
fi

SMB="$SMB_PREFIX/$1/DS-Schedule.dsbs"
WEB="$WEB_PREFIX/$1/status.txt"

# check ini file @ smb share
if [ ! -f "$SMB" ]; then
  echo "$SMB not found!"
  exit 2
fi

# check statusfile @ web share
touch $WEB
if [ "x$?" != "x0" ]; then
  echo "Problem while creating $WEB !"
  exit 3
fi

# parse dsbs ini file, create 4 arrays
read_dsbs() {
  local i
  while IFS=$'' read var; do
    # section found
    if [[ $var == \[*\] ]]; then
      section=$var
      i=0
      continue
    fi
    # check for valid entry
    case $var in
    [0-9]*=1*)
      case $section in
      "[Weekplan]")
        WEEKPLAN[$i]=${var#*|}
        i=$((i+1))
        ;;
      "[Offtimes]")
        OFFTIMES[$i]=${var#*|}
        i=$((i+1))
        ;;
      "[Events]")
        EVENTS[$i]=${var#*|}
        i=$((i+1))
        ;;
      "[Macs]")
        MACS[$i]=$var
        i=$((i+1))
        ;;
      esac
      # echo "var=$var, sektion=$section, i=$i"
      ;;
    esac
  done < "$1"
}

wolcheck_etherwake() {
  NETDEVS=`cat /proc/net/dev | grep "eth"| cut -d: -f1`
  for i in ${!MACS[@]}; do
    str=${MACS[$i]}
    str=${str#*|}
    mac=${str:0:17}
    for dev in ${NETDEVS[@]}; do
      echo $ETHERWAKE -i "$dev" "$mac"
    done
  done
}

wolcheck_wol() {
  for i in ${!MACS[@]}; do
    # 3=1|12:34:56:78:90:ef|DSB Lehrerzimmer
    str=${MACS[$i]}
    str=${str#*|}
    mac=${str:0:17}
    echo wol $mac
  done
}

# ON|MAC|Beschreibung
# [Macs]
wolcheck() {
  # wol via ether-wake
  ETHERWAKE=`which ether-wake`
  if [ ! -z $ETHERWAKE ]; then
    wolcheck_etherwake
    return 0
  fi

  # wol via wol tool
  WOL=`which wol`
  if [ ! -z $WOL ]; then
    wolcheck_wol
    return 0
  fi
}

# ON|YYYYmmdd|HHMM-HHMM|Layout|Beschreibung
function set_event() {
  cat <<EOF > $WEB
SHUTDOWN=0
NOTE=$cl_note
LAYOUT=$cl_layout
TIME=$cl_time
DATE=$cl_date
EOF
  wolcheck
  exit
}

function set_offtime() {
  cat <<EOF > $WEB
SHUTDOWN=1
NOTE=$cl_note
DATE1=$cl_date1
DATE2=$cl_date2
EOF
  exit
}

function set_weekplan() {
  cat <<EOF > $WEB
SHUTDOWN=0
NOTE=weekplan
LAYOUT=$cl_layout
TIME=$cl_time
DOW=$cl_dow
EOF
  wolcheck
  exit
}

# arrays @ schedule ini
declare -A "WEEKPLAN" "OFFTIMES" "EVENTS" "MACS"
exec 2>/dev/null

# read arrays
read_dsbs "$SMB"

# read current date, time and day of week
DATETIME=`date +%u%Y%m%d%H%M`
DOW=${DATETIME:0:1}
TODAY=${DATETIME:1:8}
CTIME=${DATETIME:9:4}

######################################################################
# 1) check events
for x in ${!EVENTS[@]}; do
  # 20170130|1100-1200|Layout2|Admin Day
  str=${EVENTS[$x]}
  cl_date=${str:0:8}
  if [ "x$cl_date" = "x$TODAY" ]; then
    str=${str#*|}
    cl_time=${str:0:9}
    cl_time1=${str:0:4}
    cl_time2=${str:5:4}
    if [ $CTIME -ge $cl_time1 -a $CTIME -le $cl_time2 ]; then
      str=${str#*|}
      cl_layout=${str%|*}
      cl_note=${str#*|}
      set_event
    fi
  fi
done

######################################################################
# 2) check offtimes
for x in ${!OFFTIMES[@]}; do
  # YYYYmmdd-YYYYmmdd|Beschreibung
  str=${OFFTIMES[$x]}
  cl_date1=${str:0:8}
  cl_date2=${str:9:8}
  if [ $TODAY -ge $cl_date1 -a $TODAY -le $cl_date2 ]; then
    cl_note=${str#*|}
    set_offtime
  fi
done

######################################################################
# 3) check weekplan
for x in ${!WEEKPLAN[@]}; do
  # 5|0730-1230|Layout1
  str=${WEEKPLAN[$x]}
  cl_dow=${str:0:1}
  if [ "x$cl_dow" = "x$DOW" ]; then
    str=${str#*|}
    cl_time=${str:0:9}
    cl_time1=${str:0:4}
    cl_time2=${str:5:4}
    if [ $CTIME -ge $cl_time1 -a $CTIME -le $cl_time2 ]; then
      cl_layout=${str#*|}
      set_weekplan
    fi
  fi
done

# default, shutdown the screen!
cl_note="nothing scheduled, shutdown"
cl_date1=$TODAY
cl_date2=$TODAY
set_offtime
